services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: localdb
      # optional; these are ignored if auth is off
      MONGODB_INITDB_ROOT_USERNAME: ""
      MONGODB_INITDB_ROOT_PASSWORD: ""
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    restart: unless-stopped
    networks:
      - local-services

volumes:
  mongodb-data:
  mongodb-config:

networks:
  local-services:
    external: true
