services:
  mongodb:
    image: mongo:8
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: localdb
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - local-services

volumes:
  mongodb-data:
  mongodb-config:

networks:
  local-services:
    external: true
