services:
  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - local-services
    command: redis-server --appendonly yes

volumes:
  redis-data:

networks:
  local-services:
    external: true
